name: Ensure API Peer Dependency

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  peer-api-check:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install semver
        run: npm install semver

      - name: Check API dependency semantics
        working-directory: packages
        run: npm run peer-api-check
