name: W3C Trace Context Integration Test

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - uses: actions/checkout@v3

      - name: Lint changelog file
        uses: avto-dev/markdown-lint@v1
        with:
          config: "/lint/config/changelog.yml"
          args: "./CHANGELOG.md"

      - name: Lint markdown files
        uses: avto-dev/markdown-lint@v1
        with:
          args: "./**/*.md"
          ignore: './CHANGELOG.md ./experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/protos ./experimental/packages/opentelemetry-exporter-metrics-otlp-proto/protos ./packages/exporter-trace-otlp-grpc/protos ./packages/exporter-trace-otlp-proto/protos'

      - name: restore npm cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            package-lock.json
            packages/*/node_modules
            packages/*/package-lock.json
            experimental/packages/*/node_modules
            experimental/packages/*/package-lock.json
          key: lint-${{ runner.os }}-${{ matrix.node_version }}-${{ hashFiles('package.json', 'packages/*/package.json', 'experimental/packages/*/package.json') }}-04142022

      # On a cache miss, install dependencies
      - name: Install dependencies
        run: |
          npm install --workspaces --ignore-scripts

      - name: Lint
        run: |
          npm run lint
          npm run lint:examples

      - name: Lint doc files
        run: |
          npm run compile
          NODE_OPTIONS=--max-old-space-size=6144 npm run docs
          npm run docs:test
